import { timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Column helpers shared by every table. Each call returns fresh builders so
 * no builder instance is shared between tables.
 */

/** uuid primary key generated by Postgres (pgcrypto's gen_random_uuid()). */
export const id = () => uuid().primaryKey().defaultRandom();

/** An audit timestamp, always timestamptz (UTC; see .claude/rules/db.md). */
export const timestamptz = () => timestamp({ withTimezone: true });

export const timestamps = () => ({
  createdAt: timestamptz().notNull().defaultNow(),
  updatedAt: timestamptz()
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});
